name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/bun.lockb') }}

      - name: Install Dependencies
        run: bun install

      - name: Checkout dataset repository
        uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: benchmark/paper
          repository: tum-db/partitioned-filters
          path: /dataset

      - name: Copy dataset data into build context
        run: |
          cp /dataset/benchmark/paper ./static/dataset

      - name: Temporary check
        run: |
          ls ./static/dataset

      - name: Build
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build
